name: Fitness Function

on: [push, pull_request]

jobs:
  fitness:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor
        run: |
          npm start &
          sleep 2

      - name: Ejecutar Fitness Functions
        run: npm test

      - name: Resultados Fitness Functions
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/